version: "3"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  neochi:
    build: .
    image: neochi-dev-base:20190424
    volumes:
      - ./src:/code
    depends_on:
      - redis
