
version: "3"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  neochi:
    build:
      context: .
      dockerfile: Dockerfile-x64
    image: mpsamurai/neochi-dev-base:20190424-x64
    volumes:
      - ./src:/code
    depends_on:
      - redis
